#!/usr/bin/env ruby

$BLACK, $RED, $GREEN, $YELLOW, $BLUE, $MAGENTA, $CYAN, $WHITE = *(30..37)


def color_code c
  "%c[%d;%d;%dm" % [0x1B, 0, c, 40]
end

def random_color
  color_code($RED + rand($WHITE - $RED))
end

def main
  $next_color = lambda { random_color }
  STDIN.each_line do |line|
    line.each_char do |c|
      print $next_color.call unless /\s/ =~ c
      print c
    end
    print color_code($WHITE)
  end
end

if __FILE__ == $PROGRAM_NAME
  main
end
