#!/usr/bin/env ruby


def color_code c
  "%c[%d;%d;%dm" % [0x1B, 0, c, 40]
end

def random_color
  color_code(31 + rand(6))
end

STDIN.each_line do |line|
  line.each_char do |c|
    print random_color unless /\s/ =~ c
    print c
  end
  print color_code(37)
end
